### ISSUE TITLE
Salt Property is missing

### ISSUE THREAD

**Issue by DaniloOliveira28** [zemirco/lockit-couchdb-adapter#9]
Hello,

I am trying to use the lockit in my webapp where I use couchdb as my DB. Well, after to instal and get working the signup process, it is looking like there is missing the "salt" property. 
After to register and verify my account, when I try to login I get the following answer from the login route:

```
"Error: salt missing at Object.exports.hash (/Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit/node_modules/lockit-login/node_modules/couch-pwd/index.js:40:26) at /Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit/node_modules/lockit-login/index.js:191:9 at /Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit-couchdb-adapter/index.js:189:7 at Request._callback (/Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit-couchdb-adapter/node_modules/nano/lib/nano.js:210:16) at Request.self.callback (/Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit-couchdb-adapter/node_modules/nano/node_modules/request/request.js:198:22) at Request.emit (events.js:110:17) at Request.<anonymous> (/Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit-couchdb-adapter/node_modules/nano/node_modules/request/request.js:1057:14) at Request.emit (events.js:129:20) at IncomingMessage.<anonymous> (/Users/DaniloOliveira/Workspace/sigalei-api/node_modules/lockit-couchdb-adapter/node_modules/nano/node_modules/request/request.js:1003:12) at IncomingMessage.emit (events.js:129:20) at _stream_readable.js:908:16 at process._tickCallback (node.js:355:11)"
```

The salt property should not be created automatically? Am I missing something?

Ty

**Comment by DaniloOliveira28** [comment]
I think that the problem is related with the fact that I am using the cloudant as my couchdb service. It does not have the users db...

**Comment by DaniloOliveira28** [comment]
Googling a little more I found it:

http://stackoverflow.com/questions/18039704/cloudant-auth-lacks-users-database

The cloudant service does not support the hash password generation... What do you suggest to get round of this problem?

**Comment by DaniloOliveira28** [comment]
Other reference:
https://github.com/doublerebel/cloudant-user
